version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    groups:
      mui:
        patterns:
          - '@mui/*'
      firebase:
        patterns:
          - 'firebase'
          - 'firebase-admin'
          - '@firebase/*'
      dev-tools:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'vitest*'
          - '@vitest/*'
          - 'storybook*'
          - '@storybook/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
